/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Memorie (https://sketchfab.com/Memorie)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-lamp-post-c466684e819a4428b6d8ed50537615e4
Title: Low-Poly Lamp Post
*/

import { useRef } from 'react'
import { Sphere, useGLTF } from '@react-three/drei'

// import lampPostScene from '../assets/3d/low-poly_lamp_post.glb'
import lampPostScene from '/3d/low-poly_lamp_post.glb'

const Lamppost = (props) => {
  const { nodes, materials } = useGLTF(lampPostScene)
	const lamppostRef = useRef();

  return (
    <group ref={lamppostRef} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LampPost_LPoly__0.geometry}
        material={materials['Scene_-_Root']}
        rotation={[-Math.PI / 2, 0, -Math.PI / 8]}
        scale={[0.3, 0.3, 0.276*0.3]}
      />

      <Sphere scale={.12} position={[-1.14,5.9,0]}>
        <meshStandardMaterial emissive={"white"} />
        <pointLight intensity={5}/>
      </Sphere>
    </group>
  )
}

useGLTF.preload('/3d/low-poly_lamp_post.glb')

export default Lamppost